### ISSUE TITLE
npm install issues on windows 

### ISSUE THREAD

**Issue by dopry** [angular-redux/form#12] opened 2017-02-17 21:31 UTC
When installing as a dependency of https://github.com/angular-redux/example-app I get the following error.

npm ERR! @angular-redux/form@6.0.1 postinstall: npm run build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular-redux/form@6.0.1 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular-redux/form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs @angular-redux/form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls @angular-redux/form
npm ERR! There is likely additional logging output above.

applies to https://github.com/angular-redux/example-app/issues/13

**Comment by SethDavenport** [comment] 2017-02-18 16:27
Can you add the entire error output from npm? What you have posted doesn't contain the actual error.

**Comment by SethDavenport** [comment] 2017-02-22 02:20
I can't reproduce the issue (Windows 8, node 6.9.5). Can you provide a few more pieces of information:

1. windows version
2. node version
3. shell: `cmd.exe`, `git-bash`, or that Windows 10 bash thing I've heard about?
4. the full npm output.

**Comment by dopry** [comment] 2017-02-23 00:54
Sorry for the delay. here are the details on just a npm install @angular-redux/form. It looks like ngc can't find typescript on the initial build.  

Windows_NT 10.0.14393
node v6.9.5
npm  v4.1.2
Powershell

```
PS G:\src\angular-redux-example-app> npm install @angular-redux/form

> @angular-redux/form@6.0.1 postinstall G:\src\angular-redux-example-app\node_modules\@angular-redux\form
> npm run build


> @angular-redux/form@6.0.1 prebuild G:\src\angular-redux-example-app\node_modules\@angular-redux\form
> npm run clean


> @angular-redux/form@6.0.1 clean G:\src\angular-redux-example-app\node_modules\@angular-redux\form
> rimraf dist


> @angular-redux/form@6.0.1 build G:\src\angular-redux-example-app\node_modules\@angular-redux\form
> ngc

module.js:471
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\src\angular-redux-example-app\node_modules\tsickle\build\src\tsickle.js:14:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DarrelO'Pry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @angular-redux/form@6.0.1 build: `ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular-redux/form@6.0.1 build script 'ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular-redux/form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular-redux/form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular-redux/form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\src\angular-redux-example-app\node_modules\@angular-redux\form\npm-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular-redux/form@6.0.1 requires a peer of @angular/common@^2.4.0 but none was installed.
npm WARN @angular-redux/form@6.0.1 requires a peer of @angular/compiler@^2.4.0 but none was installed.
npm WARN @angular-redux/form@6.0.1 requires a peer of @angular/core@^2.4.0 but none was installed.
npm WARN @angular-redux/form@6.0.1 requires a peer of @angular/forms@^2.4.0 but none was installed.
npm WARN @angular-redux/form@6.0.1 requires a peer of @angular-redux/store@^6.0.0 but none was installed.
npm WARN @angular-redux/form@6.0.1 requires a peer of redux@^3.0 but none was installed.
npm WARN @angular/forms@2.4.8 requires a peer of @angular/common@2.4.8 but none was installed.
npm WARN @angular/compiler-cli@2.4.8 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/compiler-cli@2.4.8 requires a peer of @angular/compiler@2.4.8 but none was installed.
npm WARN @angular/compiler-cli@2.4.8 requires a peer of @angular/core@2.4.8 but none was installed.
npm WARN @angular/tsc-wrapped@0.5.2 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @ngtools/webpack@1.2.10 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN @ngtools/webpack@1.2.10 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN @ngtools/webpack@1.2.10 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN tsickle@0.2.6 requires a peer of typescript@^2.0.0 but none was installed.
npm WARN Error: EPERM: operation not permitted, lstat 'G:\src\angular-redux-example-app\node_modules\url\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, lstat 'G:\src\angular-redux-example-app\node_modules\url\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'G:\\src\\angular-redux-example-app\\node_modules\\url\\node_modules' }
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DarrelO'Pry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@angular-redux/form"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! @angular-redux/form@6.0.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular-redux/form@6.0.1 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular-redux/form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular-redux/form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular-redux/form
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\src\angular-redux-example-app\npm-debug.log
```

**Comment by SethDavenport** [comment] 2017-02-24 18:13
Thanks - I'll try an dig into more this weekend.

**Comment by Shiroh1ge** [comment] 2017-03-03 21:11
Having the same problem when I tried installing this. Different error, though:

```
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in E:/Repositories/Overpro/no
de_modules/@angular/core/typings/core.d.ts, resolving symbol ɵf in E:/Repositories/Overpro/node_modules/@angular/core/typings/core.d.ts, resolving symbol ɵf in E:/Repositories/Overpro/node_modules/@angular/core/typings/core.d.ts

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! @angular-redux/form@6.0.1 build: `ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular-redux/form@6.0.1 build script 'ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular-redux/form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular-redux/form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular-redux/form
npm ERR! There is likely additional logging output above.

```
Any news on this?

**Comment by javico2609** [comment] 2017-03-20 14:08
```
 npm install angular-redux/form --save

> @angular-redux/form@6.0.1 postinstall \node_modules\@angular-redux\form
> npm run build


> @angular-redux/form@6.0.1 prebuild \node_modules\@angular-redux\form
> npm run clean


> @angular-redux/form@6.0.1 clean \node_modules\@angular-redux\form
> rimraf dist


> @angular-redux/form@6.0.1 build \node_modules\@angular-redux\form
> ngc

Error at ......../node_modules/@angular-redux/form/source/state.ts:221:25: Type 'string' does not satisfy the constraint 'object'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular-redux/form@6.0.1 build: `ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular-redux/form@6.0.1 build script 'ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular-redux/form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular-redux/form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular-redux/form
npm ERR! There is likely additional logging output above.
```

**Comment by SethDavenport** [comment] 2017-03-27 01:16
Sorry about this.  The angular ecosystem is rife with breaking changes on minor versions, and it seems we've gotten burned again.  I'm looking into what's happening here while I update to Angular 4.0.0 final.

**Comment by SethDavenport** [comment] 2017-03-27 01:17
In the meantime, if you're using typescript 2.1, I suggest winding back to ~2.0.10 - that's the latest angular 2 supports anyway.

**Comment by serhiiharbo** [comment] 2017-03-27 04:38
@dopry @javico2609 @Shiroh1ge 
Try to set typescript version in package.json of your project as 2.1.6 or lower.
I have had such problem last week and it was crashing on `ngc` command with same error output because of my ts version was 2.2.1.

**Comment by SethDavenport** [comment] 2017-04-03 01:45
angular-redux/form@6.1.1 has been released with a number of toolchain fixes - can you try upgrading?

**Closed as completed by SethDavenport** 2017-04-03 01:45 UTC
